### ISSUE TITLE
Mixin Apply Failed

### ISSUE THREAD

**Issue by dreckz** [ldtteam/Performant#25] opened 2020-04-06 19:03 UTC
**Describe the bug**
When attempting to load up the modpack, it encounters a [FATAL] error in attempting to apply and a chunk manager

**To Reproduce**
1.  Load up Performant with modpack
2.  Crash occurs on load up

**Expected behavior**
Modpack normally loads up.  Confirmed to work with the direct previous version

**Screenshots**
N/A, just crashes client

** Mod version **
Crash occurs with Performant 2.0m and 2.1m

** Logs **
Specific FATAL error:
https://paste.gg/p/anonymous/d8b6bdba285d43fba18e0c15990c1512
latest.log:
[latest.log](https://github.com/ldtteam/Performant/files/4440340/latest.log)

Note: I've tried the direct previous version [performant 1.12], and it works perfect in the modpack.

I believe this _could_ just be an incompatibility issue.

**Comment by someaddons** [comment] 2020-04-06 19:05
ye the new version is quite a bit different, did you install mixinbootstrap?

**Comment by someaddons** [comment] 2020-04-06 19:08
ye seems the issue is some other mod making it pubic, gonna change mine to public aswell

**Comment by someaddons** [comment] 2020-04-06 19:35
should be fixed on 2.02m

**Closed by someaddons** 2020-04-06 19:35 UTC
Labels: bug
