### ISSUE TITLE
[1.15.2] Incompatibility between Performant 2.05m and Lithium 0.4.6-RC3

### ISSUE THREAD

**Issue by WadeMason** [ldtteam/Performant#30] opened 2020-04-13 19:48 UTC
**Describe the bug**
Incompatibility between Performant 2.05m and Lithium 0.4.6-RC3 (Crash on world creation/load).

**To Reproduce**
1. Add Performant 2.05m and Lithium 0.4.6-RC3.
2. Attempt to create or load a world.

**Mod version**

- Performant 2.05m
- Lithium 0.4.6-RC3
- MixinBootstrap 1.0.2
- Forge 31.1.44

**Full Modlist**

- AppleSkin-mc1.15.2-forge-1.0.13.jar
- BiomesOPlenty-1.15.2-10.0.0.345-universal.jar
- Hwyla-forge-1.10.8-B72_1.15.2.jar
- jei-1.15.2-6.0.0.3.jar
- lithium-mc1.15.2-forge-0.4.6-rc3-mod.jar
- MixinBootstrap-1.0.2.jar
- OreExcavation-1.7.151.jar
- performant-1.15-2.05m.jar
- phosphor-forge-mc1.15.2-0.5.2+build.4.jar
- SereneSeasons-1.15.2-3.0.0.68-universal.jar

**Logs**
[https://gist.github.com/WadeMason/2fb8385f8c81f09f929387b334d396de](https://gist.github.com/WadeMason/2fb8385f8c81f09f929387b334d396de)

**Comment by someaddons** [comment] 2020-04-13 20:02
ye seems theres some incompatibility with lithium now, set the 
`fastSpawnRadius` config option to false to launch

**Comment by WadeMason** [comment] 2020-04-13 20:05
I did some more testing and found the same thing. Updated the original issue for accuracy.

**Comment by someaddons** [comment] 2020-04-13 20:59
should be fixed in 2.6, and found an issue where the config didnt disable stuff as intended :D

**Closed by someaddons** 2020-04-13 20:59 UTC
Labels: bug
